server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Tenta achar o arquivo. Se não achar (ex: rota /home),
        # devolve o index.html para o Flutter tratar a rota.
        try_files $uri $uri/ /index.html;
    }

    # Cache para arquivos estáticos (imagens, fontes, etc)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|ttf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}