name: myapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.1
  flutter_spinbox: ^0.13.1
  http: ^1.5.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
     - lib/imagens/logocivil.png
     - lib/imagens/pessoas.jpg
     - lib/imagens/insta.png
     - lib/imagens/whataspp.png
     - lib/imagens/user.png
