name: Docker Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Image
        run: docker build -t desaparecidos-app .
        
      - name: Test Docker Run
        run: docker run -d -p 8080:80 desaparecidos-app